### PR TITLE
Typescript support

### PR DESCRIPTION
**Pull request by tomlarkworthy**
Add Typescript to main codebase

esbuild to build /dist/index.js (reduces backed size to 50Kb)
npm publish only publishes /dist/index.js
files renamed from *.js to *.ts
eslint has TS support added

This is based on https://github.com/markusahlstrand/cloudworker-proxy/pull/130 so we have an integration test checking the final artefact still works (it does). That PR should be merged first

outstanding issue: of course our JS is not good TS so linting fails. There needs to be a ton of work to fix it, but not fixing it does not break the build process so its doesn't seem like a blocker.

fixes https://github.com/markusahlstrand/cloudworker-proxy/issues/121

### CODE REVIEW

**Comment by tomlarkworthy** [comment]
current failures are linting because of the new TS code. The actual unit and integration tests pass

**Review by markusahlstrand — APPROVED** [review]

**Comment by markusahlstrand** [comment]
This looks good but has a merge conflict on the S3 file. Any chance you could have a look @tomlarkworthy ?

**Comment by tomlarkworthy** [comment]
Yeah will fix later

**Comment by tomlarkworthy** [comment]
ok I think this merges now

**Pull request merged**
